[build]
builder = "nixpacks"

[deploy]
startCommand = "next start"
releaseCommand = "npx prisma db push --skip-generate --accept-data-loss"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
